export const cartTypes = {
    TOGGLE_CART:'TOGGLE_CART',
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_CART:'REMOVE_CART',
    CLEAR_ITEM:'CLEAR_ITEM',
    CLEAR_CART:'CLEAR_CART',
    CHECK_USER:'CHECK_USER',
}