export const userTypes = {
    SIGNIN_START:'SIGNIN_START',
    SIGNIN_FAILURE:'SIGNIN_FAILURE',
    SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
    GOOGLE_SIGNIN_START:'GOOGLE_SIGNIN_START',
    SIGNUP_START:'SIGNUP_START',
    SIGNOUT_START:'SIGNOUT_START',
    SIGNOUT_SUCCESS:'SIGNOUT_SUCCESS',
    CHECK_USER:'CHECK_USER',

}

